name: Continuous Integration

on: [push]

jobs:
  test_and_generate:
    name: test_and_generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cleanup
        run: sed -i "s/%NAME%/test/g" build.sc
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - name: Setup Mill
        uses: jodersky/setup-mill@v0.2.3
        with:
          mill-version: 0.9.7
      - name: Cache Scala
        uses: coursier/cache-action@v5
      - name: SBT Test
        run: sbt test
      - name: mill Test
        run: mill _.test
      - name: mill Test
        run: mill _.test
      - name: generate mycpu_top.v
        run: sbt 'runMain com.github.hectormips.SocTopAXI'
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: mycpu_top
          path: mycpu_top.v

  tlb_test:
    name: tlb_test
    needs: test_and_generate
    runs-on: self-hosted
    env:
      SIM_DIR: /home/hch/tlb_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download mycpu_top
        uses: actions/download-artifact@v2
        with:
          name: mycpu_top
      - name: copy to default location
        run: cp mycpu_top.v ${{env.SIM_DIR}}/xsim/srcs/
      - name: Cleanup
        run: |
          cd ${{env.SIM_DIR}}/xsim
          make clean
      - name: Run Test
        run: |
          cd ${{env.SIM_DIR}}/xsim
          make

  func_test:
    name: func_test
    needs: test_and_generate
    runs-on: self-hosted
    env:
      SIM_DIR: /home/hch/sim
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download mycpu_top
        uses: actions/download-artifact@v2
        with:
          name: mycpu_top
      - name: copy to default location
        run: cp mycpu_top.v ${{env.SIM_DIR}}/xsim/srcs/
      - name: Cleanup
        run: |
          cd ${{env.SIM_DIR}}/xsim
          make clean
      - name: Run Test
        run: |
          cd ${{env.SIM_DIR}}/xsim
          make

  perf_test:
    name: perf_test
    needs: test_and_generate
    runs-on: self-hosted
    env:
      SIM_DIR: /home/hch/perf_sim
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download mycpu_top
        uses: actions/download-artifact@v2
        with:
          name: mycpu_top
      - name: copy to default location
        run: cp mycpu_top.v ${{env.SIM_DIR}}/xsim/srcs/
      - name: Cleanup
        run: |
          cd ${{env.SIM_DIR}}/xsim
          make clean
      - name: Run Test
        run: |
          cd ${{env.SIM_DIR}}/xsim
          make
          
  bit_generate:
    name: bit_generate
    needs: perf_test
    runs-on: self-hosted
    env:
      SIM_DIR: /home/hch/bitgenerate
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download mycpu_top
        uses: actions/download-artifact@v2
        with:
          name: mycpu_top
      - name: copy to default location
        run: cp mycpu_top.v ${{env.SIM_DIR}}/rtl/myCPU/
      - name: Run Test
        run: |
          cd ${{env.SIM_DIR}}/
          make
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: mycpu_bit
          path: ${{env.SIM_DIR}}/run_vivado/mycpu_prj1/mycpu.runs/impl_1/soc_axi_lite_top.bit

  soc_generate:
    name: soc_generate
    needs: perf_test
    runs-on: self-hosted
    env:
      SIM_DIR: /home/hch/soc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download mycpu_top
        uses: actions/download-artifact@v2
        with:
          name: mycpu_top
      - name: copy to default location
        run: cp mycpu_top.v ${{env.SIM_DIR}}/rtl/cpu232/
      - name: Run Test
        run: |
          cd ${{env.SIM_DIR}}/
          make
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: mycpu_bit
          path: ${{env.SIM_DIR}}/vivado_xpr/project_1/project_1/project_1.runs/impl_1/soc_up_top.bit
