package com.github.hectormips

import chisel3._
import chisel3.util.experimental.forceName

class AXIIO extends Bundle {
  // axi
  val arid   : UInt = Output(UInt(4.W))
  val araddr : UInt = Output(UInt(32.W))
  val arlen  : UInt = Output(UInt(8.W))
  val arsize : UInt = Output(UInt(3.W))
  val arburst: UInt = Output(UInt((2).W))
  val arlock : UInt = Output(UInt((2).W))
  val arcache: UInt = Output(UInt((4).W))
  val arprot : UInt = Output(UInt((3).W))
  val arvalid: Bool = Output(Bool())
  val arready: Bool = Input(Bool())
  val rid    : UInt = Input(UInt((4).W))
  val rdata  : UInt = Input(UInt((32).W))
  val rresp  : UInt = Input(UInt((2).W))
  val rlast  : UInt = Input(Bool())
  val rvalid : Bool = Input(Bool())
  val rready : Bool = Output(Bool())
  val awid   : UInt = Output(UInt((4).W))
  val awaddr : UInt = Output(UInt((32).W))
  val awlen  : UInt = Output(UInt((8).W))
  val awsize : UInt = Output(UInt((3).W))
  val awburst: UInt = Output(UInt((2).W))
  val awlock : UInt = Output(UInt((2).W))
  val awcache: UInt = Output(UInt((4).W))
  val awprot : UInt = Output(UInt((3).W))
  val awvalid: Bool = Output(Bool())
  val awready: Bool = Input(Bool())
  val wid    : UInt = Output(UInt((4).W))
  val wdata  : UInt = Output(UInt((32).W))
  val wstrb  : UInt = Output(UInt((4).W))
  val wlast  : Bool = Output(Bool())
  val wvalid : Bool = Output(Bool())
  val wready : Bool = Input(Bool())
  val bid    : UInt = Input(UInt((4).W))
  val bresp  : UInt = Input(UInt((2).W))
  val bvalid : Bool = Input(Bool())
  val bready : Bool = Output(Bool())


  forceName(arid, "arid")
  forceName(araddr, "araddr")
  forceName(arlen, "arlen")
  forceName(arsize, "arsize")
  forceName(arburst, "arburst")
  forceName(arlock, "arlock")
  forceName(arcache, "arcache")
  forceName(arprot, "arprot")
  forceName(arvalid, "arvalid")
  forceName(arready, "arready")
  forceName(rid, "rid")
  forceName(rdata, "rdata")
  forceName(rresp, "rresp")
  forceName(rlast, "rlast")
  forceName(rvalid, "rvalid")
  forceName(rready, "rready")
  forceName(awid, "awid")
  forceName(awaddr, "awaddr")
  forceName(awlen, "awlen")
  forceName(awsize, "awsize")
  forceName(awburst, "awburst")
  forceName(awlock, "awlock")
  forceName(awcache, "awcache")
  forceName(awprot, "awprot")
  forceName(awvalid, "awvalid")
  forceName(awready, "awready")
  forceName(wid, "wid")
  forceName(wdata, "wdata")
  forceName(wstrb, "wstrb")
  forceName(wlast, "wlast")
  forceName(wvalid, "wvalid")
  forceName(wready, "wready")
  forceName(bid, "bid")
  forceName(bresp, "bresp")
  forceName(bvalid, "bvalid")
  forceName(bready, "bready")


}
