package com.github.hectormips

import chisel3._
import chisel3.util.experimental.forceName

class AXIIO extends Bundle {
  // axi
  val arid   : UInt = Output(UInt(8.W))
  val araddr : UInt = Output(UInt(64.W))
  val arlen  : UInt = Output(UInt(16.W))
  val arsize : UInt = Output(UInt(6.W))
  val arburst: UInt = Output(UInt(4.W))
  val arlock : UInt = Output(UInt(4.W))
  val arcache: UInt = Output(UInt(8.W))
  val arprot : UInt = Output(UInt(6.W))
  val arvalid: UInt = Output(UInt(2.W))
  val arready: UInt = Input(UInt(2.W))
  val rid    : UInt = Input(UInt(8.W))
  val rdata  : UInt = Input(UInt(64.W))
  val rresp  : UInt = Input(UInt(4.W))
  val rlast  : UInt = Input(UInt(2.W))
  val rvalid : UInt = Input(UInt(2.W))
  val rready : UInt = Output(UInt(2.W))
  val awid   : UInt = Output(UInt(8.W))
  val awaddr : UInt = Output(UInt(64.W))
  val awlen  : UInt = Output(UInt(16.W))
  val awsize : UInt = Output(UInt(6.W))
  val awburst: UInt = Output(UInt(4.W))
  val awlock : UInt = Output(UInt(4.W))
  val awcache: UInt = Output(UInt(8.W))
  val awprot : UInt = Output(UInt(6.W))
  val awvalid: UInt = Output(UInt(2.W))
  val awready: UInt = Input(UInt(2.W))
  val wid    : UInt = Output(UInt(8.W))
  val wdata  : UInt = Output(UInt(64.W))
  val wstrb  : UInt = Output(UInt(8.W))
  val wlast  : UInt = Output(UInt(2.W))
  val wvalid : UInt = Output(UInt(2.W))
  val wready : UInt = Input(UInt(2.W))
  val bid    : UInt = Input(UInt(8.W))
  val bresp  : UInt = Input(UInt(4.W))
  val bvalid : UInt = Input(UInt(2.W))
  val bready : UInt = Output(UInt(2.W))


  forceName(arid, "arid")
  forceName(araddr, "araddr")
  forceName(arlen, "arlen")
  forceName(arsize, "arsize")
  forceName(arburst, "arburst")
  forceName(arlock, "arlock")
  forceName(arcache, "arcache")
  forceName(arprot, "arprot")
  forceName(arvalid, "arvalid")
  forceName(arready, "arready")
  forceName(rid, "rid")
  forceName(rdata, "rdata")
  forceName(rresp, "rresp")
  forceName(rlast, "rlast")
  forceName(rvalid, "rvalid")
  forceName(rready, "rready")
  forceName(awid, "awid")
  forceName(awaddr, "awaddr")
  forceName(awlen, "awlen")
  forceName(awsize, "awsize")
  forceName(awburst, "awburst")
  forceName(awlock, "awlock")
  forceName(awcache, "awcache")
  forceName(awprot, "awprot")
  forceName(awvalid, "awvalid")
  forceName(awready, "awready")
  forceName(wid, "wid")
  forceName(wdata, "wdata")
  forceName(wstrb, "wstrb")
  forceName(wlast, "wlast")
  forceName(wvalid, "wvalid")
  forceName(wready, "wready")
  forceName(bid, "bid")
  forceName(bresp, "bresp")
  forceName(bvalid, "bvalid")
  forceName(bready, "bready")


}
